export const schema = gql`
  """
  Representation of Category.
  """
  type Category {
    "Description for id."
    id: Int!

    "Description for MenuItem."
    MenuItem: [MenuItem]!

    "Description for createdAt."
    createdAt: DateTime!

    "Description for name."
    name: String!
  }

  """
  About queries
  """
  type Query {
    "Fetch Categories."
    categories: [Category!]! @requireAuth

    "Fetch a Category by id."
    category(id: Int!): Category @requireAuth
  }

  """
  Autogenerated input type of InputCategory.
  """
  input CreateCategoryInput {
    "Description for name."
    name: String!
  }

  """
  Autogenerated input type of UpdateCategory.
  """
  input UpdateCategoryInput {
    "Description for name."
    name: String
  }

  """
  About mutations
  """
  type Mutation {
    "Creates a new Category."
    createCategory(input: CreateCategoryInput!): Category! @requireAuth

    "Updates an existing Category."
    updateCategory(id: Int!, input: UpdateCategoryInput!): Category!
      @requireAuth

    "Deletes an existing Category."
    deleteCategory(id: Int!): Category! @requireAuth
  }
`
