export const schema = gql`
  """
  Representation of OrderDelivery.
  """
  type OrderDelivery {
    "Description for id."
    id: Int!

    "Description for addres."
    addres: String!

    "Description for phone."
    phone: String!

    "Description for order."
    order: Order!

    "Description for customer."
    customer: User!

    "Description for orderId."
    orderId: Int!

    "Description for userId."
    userId: Int!
  }

  """
  About queries
  """
  type Query {
    "Fetch OrderDeliveries."
    orderDeliveries: [OrderDelivery!]! @requireAuth

    "Fetch a OrderDelivery by id."
    orderDelivery(id: Int!): OrderDelivery @requireAuth
  }

  """
  Autogenerated input type of InputOrderDelivery.
  """
  input CreateOrderDeliveryInput {
    "Description for addres."
    addres: String!

    "Description for phone."
    phone: String!

    "Description for orderId."
    orderId: Int!

    "Description for userId."
    userId: Int!
  }

  """
  Autogenerated input type of UpdateOrderDelivery.
  """
  input UpdateOrderDeliveryInput {
    "Description for addres."
    addres: String

    "Description for phone."
    phone: String

    "Description for orderId."
    orderId: Int

    "Description for userId."
    userId: Int
  }

  """
  About mutations
  """
  type Mutation {
    "Creates a new OrderDelivery."
    createOrderDelivery(input: CreateOrderDeliveryInput!): OrderDelivery!
      @requireAuth

    "Updates an existing OrderDelivery."
    updateOrderDelivery(
      id: Int!
      input: UpdateOrderDeliveryInput!
    ): OrderDelivery! @requireAuth

    "Deletes an existing OrderDelivery."
    deleteOrderDelivery(id: Int!): OrderDelivery! @requireAuth
  }
`
