export const schema = gql`
  """
  Representation of Table.
  """
  type Table {
    "Description for id."
    id: Int!

    "Description for name."
    name: String!

    "Description for restaurant."
    restaurant: Restaurant!

    "Description for restaurantId."
    restaurantId: Int!

    "Description for Order."
    Order: [Order]!
  }

  """
  About queries
  """
  type Query {
    "Fetch Tables."
    tables: [Table!]! @requireAuth

    "Fetch a Table by id."
    table(id: Int!): Table @requireAuth
  }

  """
  Autogenerated input type of InputTable.
  """
  input CreateTableInput {
    "Description for name."
    name: String!

    "Description for restaurantId."
    restaurantId: Int!
  }

  """
  Autogenerated input type of UpdateTable.
  """
  input UpdateTableInput {
    "Description for name."
    name: String

    "Description for restaurantId."
    restaurantId: Int
  }

  """
  About mutations
  """
  type Mutation {
    "Creates a new Table."
    createTable(input: CreateTableInput!): Table! @requireAuth

    "Updates an existing Table."
    updateTable(id: Int!, input: UpdateTableInput!): Table! @requireAuth

    "Deletes an existing Table."
    deleteTable(id: Int!): Table! @requireAuth
  }
`
